baseurl = "http://clean-jsta-rbind-io-2a1533.lisdi-pages.lanl.gov/"
languageCode = "en-us"
title = "Jemma Stachelek"
theme = "hugo-lithium-theme"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$"]
enableEmoji = true
enableRobotsTXT = true
footnotereturnlinkcontents = "↩"
rssLimit = 30

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "Products"
    url = "/products/"
    weight = 2
[[menu.main]]
    name = "CV"
    url = "/cv/"
    weight = 3

[params]
    description = "Personal website of Jemma Stachelek"
    dateFormat = "2006/01/02"
    customCSS = ["css/style-new.css", "css/custom.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Homepage link"
    
    [params.social]
    github = "jsta"
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
