---
title: "Jem posting: a notice of my name and gender"
date: '2021-06-04'
slug: jem-posting
---

This post serves as a notice of my name and gender. **I go by Jemma or "Jem" for short and I use she/her pronouns**.

I considered writing a long post touching on transgender 101 topics, my personal journey, and the hopes/fears associated with being transgender. However, given that I am not a scholar of transgender science/philosophy, I don't want to appear to speak for all trans people, and my story is not really that unique among trans people, I've decided to simply curate a list of links at the end of this post. The personal essays broadly reflect my own experience.

I ask that everyone reading this use my current name Jem (Jemma) and pronouns (she/her) whenever possible, educate themselves to at least a minimal degree on transgender topics (see References), and give themselves space for reflection on their own gender. If you are questioning your gender and find in-person support-groups/talk-therapy intimidating, unavailable, or insufficient, know that there are informal online communities filled with people who want to help.

## References

This is not a comprehensive list. It has recency bias, it is heavily slanted towards transgender women, and does not really touch on issues of [intersectionality](https://en.wikipedia.org/wiki/Intersectionality). 

### Trans 101

* https://pflag.org/sites/default/files/Our%20Trans%20Loved%20Ones.pdf

### Personal essays

* https://sjmielke.com/sabrina.htm

* https://medium.com/bits-and-behavior/im-trans-call-me-amy-8a72a3951964

* https://essays.djnavarro.net/post/a-lexical-decision/

<!-- ## Tweet -->

<!-- [blog] Jem posting: a notice of my name and gender | https://jsta.rbind.io/blog/jem-posting -->
