name: awesome_bot

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby 2.6
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: Checks
      run: |        
        gem install awesome_bot        
        awesome_bot --allow-redirect --allow-dupe --allow 503 --set-timeout 300 --allow-ssl --white-list "sciencebase.gov","lanl.gov","npr.org","twitter.com","wisc.edu","teos-10.org" static/pdf/cv.tex content/*.md
